// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:da2d7bcd-9674-4e61-a2eb-f5693af30b21',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'loginproject-hosting-mobilehub-1062896856',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd2v1yaihxqbgci.cloudfront.net',
    'aws_mobile_analytics_app_id': '6fac3458af8c459eb102ad684c2656e6',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'd924780a-361c-11e8-bae5-871246b01dfc',
    'aws_project_name': 'LoginProject-2018-04-01-19-23-29',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'loginproject-mobilehub-1062896856',
}

export default awsmobile;
